#!/bin/bash

cd # make sure we are in the correct working directory
pushd `dirname $0`

# get current system time (unix seconds)
time=`date -u +%s`

# take a picture
raspistill --awb incandescent -vf -hf -t 1 -w 800 -h 600 -o pic.jpg

# get brightness and difference
analysis=(`./analyse pic.jpg prev.jpg`)

# save this as the previous picture ready for next time
cp pic.jpg prev.jpg

# reduce size (jpegoptim 1.3.0 from http://www.kokkonen.net/tjko/projects.html)
/usr/local/bin/jpegoptim -o -vvvv --strip-all -m60 pic.jpg

# set readable to all, since jpegoptim changes the permissions
chmod +r pic.jpg

# construct the url to send to
endpoint=`cat endpoint`
url="$endpoint?time=$time&brightness=${analysis[0]}&difference=${analysis[1]}"
echo $url

# upload it
curl -v --data-urlencode data@pic.jpg "$url"

# change directory back
popd